### ISSUE TITLE
Add ONVIF MoveStatus

### ISSUE THREAD

**Issue by klipper-vp** [roleoroleo/sonoff-hack#174]
here unfortunately it didn't work giving this error
using frigate latest version

Timestamp
2024-08-15 16:21:29
Tag
frigate.ptz.autotrack
Message
Disabling autotracking for sonoff-camera: ONVIF MoveStatus not supported

Firmware Version | 0.1.7
Base Version | V2524.1.412build20220712
Model | GK-200MP2B

**Comment by roleoroleo** [comment]
I'm not able to detect if the cam is moving or not, because I didn't find an "api".
So the configuration file contains a "echo 0" ->https://github.com/roleoroleo/sonoff-hack/blob/f55c5daf2dc0981f7792de4a683ee8b370e704ce/src/static/static/sonoff-hack/script/service.sh#L144
It means: the cam isn't moving.
Is your configuration file correct? It should work.
