### ISSUE TITLE
ONVIF not working

### ISSUE THREAD

**Issue by piechade** [roleoroleo/sonoff-hack#71]
Is the version 27620201103 working with this hack?
I can't get it working with Synology Surveillance Station or Onvif Device Manager.

Update: working with Onvif Device Manager.
Can somebody help me with the Synology config?

**Comment by roleoroleo** [comment]
Check this long thread:
https://github.com/roleoroleo/sonoff-hack/issues/16

IMHO the onvif implementation by Synology is not standard.
I successfully connected a DS214e with this cam but other users found problems.

**Comment by piechade** [comment]
What can I provide you to find the issue together?

**Comment by roleoroleo** [comment]
You should capture the traffic between the cam and the nas.
tcpdump for example.
If you are able to capture it inside the nas it's probably better.
Otherwise you can download tcpdump and run tcpdump in your cam (check this repo).
Run it with this command line:
`tcpdump -i wlan0 -w /tmp/sd/capture.pcap`

**Comment by piechade** [comment]
It's working, but I have no idea why and what was wrong before.
