### ISSUE TITLE
Can I apply the firmware on a GK-200MP2B with a v28XXXXXX version???

### ISSUE THREAD

**Issue by oscarare** [roleoroleo/sonoff-hack#77]
Can I apply the firmware on a GK-200MP2B with a v28XXXXXX version???

**Comment by roleoroleo** [comment]
I don't know, at the moment.
I have to test it.

**Comment by DelusionalAI** [comment]
It worked for me.

**Comment by riwich** [comment]
Not for me.. With Camera firmware v28xxxx and hack v0.09, everything worked fine. Since I updated to hack v0.1.1 I cannot longer connect to the camera with the eWeLink-App. Local RTSP-Stream and http OK. Of course, the Cloud-Functionality is enabled. Anyway, I had to reconnect the Cam to the eWeLink-App with a blank Micro SD-Card to use it in the eWeLink-App again... Unfortunately I cannot test it further at the moment, the camera is now running without the hack..

**Comment by roleoroleo** [comment]
@riwich 
I'm trying to fix this problem.
Do you want to try a "patch"?
Overwrite system.sh
[system.sh.tar.gz](https://github.com/roleoroleo/sonoff-hack/files/8162627/system.sh.tar.gz)

**Comment by riwich** [comment]
Hello roleoroleo
Thank you very much for your efforts! Does the problem have to do with the
Sonoff Firware, or perhaps with new measures in the Sonoff Cloud? I would
very much like to test the patch, however I only have one "Sonoff
GK-200MP2B" available at the moment, and it has to run. I cannot experiment
with it... However, another "Sonoff GK-200MP2B" has been ordered and is on
its way. As soon as it arrives, I will be able to test it!



Am Di., 1. März 2022 um 16:20 Uhr schrieb roleo ***@***.***>:

**Comment by roleoroleo** [comment]
Ok, thank you.
I think the problem arises when I delete the admin user from the database.

**Comment by riwich** [comment]
OK, soon I have my "Spare Cam", I will test it and report the result's!
Thanks again!

Am Di., 1. März 2022 um 18:17 Uhr schrieb roleo ***@***.***>:

**Comment by roleoroleo** [comment]
This one is better:
[system.sh.tar.gz](https://github.com/roleoroleo/sonoff-hack/files/8168746/system.sh.tar.gz)

**Comment by riwich** [comment]
My God, the Sonoff camera with its stupid sound setup is really bothering
me by now...
Unfortunately, the last version of the "system.sh" did not bring the
desired success. Even worse, with this version the camera seems to hang up
completely, there is no RTSP stream available on the local network, even
the websites are no longer accessible. By the way, the firmware version of
my camera is 28520210714.

Am Mi., 2. März 2022 um 11:24 Uhr schrieb roleo ***@***.***>:

**Comment by roleoroleo** [comment]
Chek if the file is properly installed.
Windows/linux CR/LF...
Permissions...

**Comment by riwich** [comment]
Hello roleoroleo!

Finally, it worked! The problem was my faulty Micro-SD card reader...
Meanwhile v0.1.1 with the updated "system.sh" works on both of my Sonoff
cameras. One camera runs with Sonoff firmware "27620201103", the other with
"28920211123".

Thank you for your work and patience!

Regards,
Thomas

Am Mo., 7. März 2022 um 08:56 Uhr schrieb roleo ***@***.***>:

**Comment by kfulko** [comment]
Works with camera version '40620220309'
